container:
  image: cirrusci/android-sdk:27

test_task:
  gradle_cache:
    folder: ~/.gradle/caches
  test_script: ./gradlew testFlossDebugUnitTest lintFlossDebug -s
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/4.5/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete