dist: trusty
sudo: required

language: android

jdk:
  - openjdk8

before_install:
  # Install SDK license so Android Gradle plugin can install dependencies.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew testFlossDebugUnitTest evaluateViolations -s

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android
