dist: trusty
sudo: required

language: android

jdk:
  - openjdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.1
    - android-28

    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+

before_install:
  # Install SDK license so Android Gradle plugin can install dependencies.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.1"

script:
  - ./gradlew testFlossDebugUnitTest evaluateViolations -s

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android
